version: '3.8'

services:
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: database
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        ports:
        - "9906:3306"
        volumes:
        - ./db.sql:/docker-entrypoint-initdb.d/db.sql

    web:
        build: .
        ports:
        - "80:80"
        - "443:443"
        volumes:
        - ./App/:/var/www/html/
        networks:
        - default
networks:
  default:
